python snapshot_finetune.py --device $1 --walk-len 1 --argus $2
python snapshot_finetune.py --device $1 --walk-len 2 --argus $2
python snapshot_finetune.py --device $1 --walk-len 3 --argus $2
python snapshot_finetune.py --device $1 --walk-len 5 --argus $2
python snapshot_finetune.py --device $1 --walk-len 7 --argus $2
python snapshot_finetune.py --device $1 --walk-len 8 --argus $2
#python snapshot_finetune.py --device $1 --walk-len 9 --argus $2
#python snapshot_finetune.py --device $1 --walk-len 10 --argus $2
#python snapshot_finetune.py --device $1 --walk-len 16 --argus $2
