python gnn_finetune.py --size med --device 1 --walk-len 2
python gnn_finetune.py --size med --device 1 --walk-len 1
python gnn_finetune.py --size med --device 1 --walk-len 0
python gnn_finetune.py --size med --device 1 --walk-len 4
python gnn_finetune.py --size med --device 1 --walk-len 6
python gnn_finetune.py --size med --device 1 --walk-len 8
python gnn_finetune.py --size med --device 1 --walk-len 10

#python rw_finetune.py --size tiny --device 1 --walk-len 2
#python rw_finetune.py --size mini --device 1 --walk-len 2
#python rw_finetune.py --size med --device 1 --walk-len 2
#python rw_finetune.py --size tiny --device 1 --walk-len 4
#python rw_finetune.py --size mini --device 1 --walk-len 4
#python rw_finetune.py --size med --device 1 --walk-len 4
#python rw_finetune.py --size tiny --device 1 --walk-len 6
#python rw_finetune.py --size mini --device 1 --walk-len 6
#python rw_finetune.py --size med --device 1 --walk-len 6
#python rw_finetune.py --size tiny --device 1 --walk-len 8
#python rw_finetune.py --size mini --device 1 --walk-len 8
#python rw_finetune.py --size med --device 1 --walk-len 8
#python rw_finetune.py --size tiny --device 1 --walk-len 10
#python rw_finetune.py --size mini --device 1 --walk-len 10
#python rw_finetune.py --size med --device 1 --walk-len 10
#python rw_finetune.py --size tiny --device 1 --walk-len 1
#python rw_finetune.py --size mini --device 1 --walk-len 1
#python rw_finetune.py --size med --device 1 --walk-len 1
#python rw_finetune.py --size tiny --device 1 --walk-len 0
#python rw_finetune.py --size mini --device 1 --walk-len 0
#python rw_finetune.py --size med --device 1 --walk-len 0